server:
  port: 9000
 
eureka:
 client:
   service-url:
    defaultZone: http://localhost:8761/eureka/
    
spring:
  application:
    name: api_gateway

  cloud:
    gateway:
      routes:
      - id : PASSENGER-MANAGEMENET-SERVICE
        uri:
         http://localhost:8082/
        predicates:
        - Path=/passenger/find/** , /passenger/all, /passenger/update, /passenger/delete/**, /passenger/add, /passenger/login, /passenger/bylocation/**, /passenger/byusername/**, /passenger/byphone/**, /passenger/authenticate
      - id : ADMIN-MANAGEMENT-SERVICE
        uri:
         http://localhost:8081/
        predicates:
        - Path=/admin/find/** , /admin/all, /admin/update, /admin/delete/**, /admin/add, /admin/login, /admin/bylocation/**, /admin/byusername/**, /admin/byphone/**, /authenticate
        